language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  #limit gradle jvm memory usage
  - GRADLE_OPTS=-Xmx512m

  - secure: Da9Brv5WKCE3z0bp5u52X1Rqul5C/r7idGj/yLhHnlEvHXPDQHaGXEQw4fNhRkB586lx6xilO8sra2FHoLDMKsqwE0h2+NKsrHQepTSFOR/fp/otoA/kiBue23ZfhsAEFn/uliVU36xLkt+LsyVqSKa+9JKDA5z1hXSemXGGVGw=
before_install:
# Added from hellbender public
- sudo mkdir -p /usr/local/lib/R/
- sudo mkdir -p site-library
- sudo ln -sFv ~/site-library /usr/local/lib/R/site-library
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"
- sudo apt-get update
- sudo apt-get install -y --force-yes r-base-dev=3.1.3-1trusty
- sudo apt-get install -y --force-yes r-base-core=3.1.3-1trusty
- sudo Rscript scripts/install_R_packages.R
# Install git-lfs, and fetch the large test files
- sudo bash scripts/install_git_lfs.sh

after_success:
- ./gradlew jacocoTestReport coveralls

after_failure:
- dmesg | tail -100
